In [16]:
import pandas as pd
import numpy as np

In [27]:
df_tr=pd.read_csv("../bact_refseq_TR.csv")
df_tr.columns=['ASV_TR','Sequence']
df_tr.head()

,ASV_TR,Sequence
0,ASV_1;seqs=64426425;samples=49,AGCGCAGGCGGTTTCTTAAGTCTGATGTGAAAGCCCCCGGCTCAAC...
1,ASV_2;seqs=32690688;samples=262,AGCGCAGGCGGTTTGATAAGTCTGAAGTTAAAGGCTGTGGCTCAAC...
2,ASV_3;seqs=25256794;samples=355,GGAGCAGGCGGCAGCAAGGGTCTGTGGTGAAAGCCTGAAGCTTAAC...
3,ASV_4;seqs=24289622;samples=116,TGCGTAGGTGGCGTACTAAGTCTGTAGTAAAAGGCAATGGCTCAAC...
4,ASV_5;seqs=13168465;samples=229,AGCGCAGGCGGTTTGATAAGTCTGAAGTTAAAGGCTGTGGCTCAAC...

In [28]:
df_cl=pd.read_csv("tblASVtaxonomy_silva138_bact.csv")
df_cl = df_cl[['ASV','Sequence']]
df_cl.columns = ['ASV_CL','Sequence']
df_cl.head()

      ASV_CL                                           Sequence
0      ASV_1  AGCGCAGGCGGTTGCTTAGGTCTGATGTGAAAGCCTTCGGCTTAAC...
1     ASV_10  AGCGTAGACGGAAGAGCAAGTCTGATGTGAAAGGCTGGGGCTTAAC...
2    ASV_100  AGCGTAGATGGATGTTTAAGTCAGTTGTGAAAGTTTGCGGCTCAAC...
3   ASV_1000  TGCGTAGGTGGTTTCTTAAGTCAGAGGTGAAAGGCTACGGCTCAAC...
4  ASV_10000  AGCGTAGACGGTGTGGCAAGTCTGATGTGAAAGGCATGGGCTCAAC...

In [29]:
df = pd.merge(df_tr, df_cl, left_on='Sequence', right_on='Sequence', how='outer')
df['ASV'] = df['ASV_CL']
df.loc[df['ASV_CL'].isnull(),'ASV'] = [x.split(';')[0]+'_TR' for x in df.loc[df['ASV_CL'].isnull(),'ASV_TR']]
assert len(df[df.ASV_CL.isnull()]) == len(set(df[df.ASV_CL.isnull()].ASV))
df

,ASV_TR,Sequence,ASV_CL,ASV
0,ASV_1;seqs=64426425;samples=49,AGCGCAGGCGGTTTCTTAAGTCTGATGTGAAAGCCCCCGGCTCAAC...,ASV_2,ASV_2
1,ASV_2;seqs=32690688;samples=262,AGCGCAGGCGGTTTGATAAGTCTGAAGTTAAAGGCTGTGGCTCAAC...,ASV_8,ASV_8
2,ASV_3;seqs=25256794;samples=355,GGAGCAGGCGGCAGCAAGGGTCTGTGGTGAAAGCCTGAAGCTTAAC...,ASV_6,ASV_6
3,ASV_4;seqs=24289622;samples=116,TGCGTAGGTGGCGTACTAAGTCTGTAGTAAAAGGCAATGGCTCAAC...,ASV_19,ASV_19
4,ASV_5;seqs=13168465;samples=229,AGCGCAGGCGGTTTGATAAGTCTGAAGTTAAAGGCTGTGGCTCAAC...,ASV_16,ASV_16
...,...,...,...,...
18680,NaN,GGAGCAGGCGGCAGCAAGGGTCTGTGGTGAAAGCCTGAAGCTTAAC...,ASV_9992,ASV_9992
18681,NaN,AGCGTAGACGGTGTTGCAAGTCTGATGTGAAAGGCGGGGGCTCAAC...,ASV_9994,ASV_9994
18682,NaN,AGCGTAGACGGAGCAGCAAGTCTGATGTGAAAACCCGGGGCTCAAC...,ASV_9996,ASV_9996
18683,NaN,AGCGTAGACGGTGTTGCAAGTCTGATGTGAAAGGCGGGGGCTCAAC...,ASV_9997,ASV_9997
18684,NaN,CACGCAGGCGGTCTGTCAAGTCGGATGTGAAATCCCCGGGCTCAAC...,ASV_9998,ASV_9998

In [21]:
ofile = open("bact_seqs.fasta", "w")

for name, seq in zip(df.ASV, df.Sequence):
    ofile.write(">" + name + "\n" +seq + "\n")
ofile.close()

In [22]:
df_tax = pd.read_csv("tblASVtaxonomy_silva138_bact.csv")
df_tax

,ASV,Sequence,Kingdom,Phylum,Class,Order,Family,Genus,LowestClassifiedTaxa,ConfidenceKingdom,ConfidencePhylum,ConfidenceClass,ConfidenceOrder,ConfidenceFamily,ConfidenceGenus,TaxonomyColor,TaxonomyColorOrder
0,ASV_1,AGCGCAGGCGGTTGCTTAGGTCTGATGTGAAAGCCTTCGGCTTAAC...,Bacteria,Firmicutes,Bacilli,Lactobacillales,Lactobacillaceae,Lactobacillus,Lactobacillus,100,100,100,100,100,100,#1635A4,163
1,ASV_10,AGCGTAGACGGAAGAGCAAGTCTGATGTGAAAGGCTGGGGCTTAAC...,Bacteria,Firmicutes,Clostridia,Lachnospirales,Lachnospiraceae,Blautia,Blautia,100,100,100,100,100,93,#AD998C,7
2,ASV_100,AGCGTAGATGGATGTTTAAGTCAGTTGTGAAAGTTTGCGGCTCAAC...,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,Bacteroidaceae,Bacteroides,Bacteroides,100,100,100,100,100,100,#16DDD3,44
3,ASV_1000,TGCGTAGGTGGTTTCTTAAGTCAGAGGTGAAAGGCTACGGCTCAAC...,Bacteria,Firmicutes,Clostridia,Peptostreptococcales-Tissierellales,Peptostreptococcaceae,Romboutsia,Romboutsia,100,100,100,100,100,100,#BEA89A,21
4,ASV_10000,AGCGTAGACGGTGTGGCAAGTCTGATGTGAAAGGCATGGGCTCAAC...,Bacteria,Firmicutes,Clostridia,Lachnospirales,Lachnospiraceae,Blautia,Blautia,100,100,100,100,100,100,#BEA89A,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17860,ASV_9992,GGAGCAGGCGGCAGCAAGGGTCTGTGGTGAAAGCCTGAAGCTTAAC...,Bacteria,Firmicutes,Bacilli,Erysipelotrichales,Erysipelatoclostridiaceae,Erysipelatoclostridium,Erysipelatoclostridium,100,100,100,100,100,100,#FBA22E,84
17861,ASV_9994,AGCGTAGACGGTGTTGCAAGTCTGATGTGAAAGGCGGGGGCTCAAC...,Bacteria,Firmicutes,Clostridia,Lachnospirales,Lachnospiraceae,Blautia,Blautia,100,100,100,100,100,95,#BEA89A,21
17862,ASV_9996,AGCGTAGACGGAGCAGCAAGTCTGATGTGAAAACCCGGGGCTCAAC...,Bacteria,Firmicutes,Clostridia,Lachnospirales,Lachnospiraceae,[Ruminococcus] torques group,[Ruminococcus] torques group,100,100,100,100,100,99,#BEA89A,21
17863,ASV_9997,AGCGTAGACGGTGTTGCAAGTCTGATGTGAAAGGCGGGGGCTCAAC...,Bacteria,Firmicutes,Clostridia,Lachnospirales,Lachnospiraceae,Blautia,Blautia,100,100,100,100,100,89,#BEA89A,21
17864,ASV_9998,CACGCAGGCGGTCTGTCAAGTCGGATGTGAAATCCCCGGGCTCAAC...,Bacteria,Proteobacteria,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella,100,100,100,100,99,87,#EE2C2C,210

In [30]:
df_taxa = pd.read_csv("../Silva/tax_silva.csv")
df_boot = pd.read_csv("../Silva/boot_silva.csv")
df_boot.columns= ['Confidence'+x for x in df_boot.columns]
df_new = pd.merge(df_taxa, df_boot, left_index=True, right_index=True, how='inner')
df_new = pd.merge(df[['ASV','Sequence']].set_index('ASV'), df_new, left_index=True, right_index=True, how='inner')
df_new.index.name='ASV'
df_new

,Sequence,Kingdom,Phylum,Class,Order,Family,Genus,Species,ConfidenceKingdom,ConfidencePhylum,ConfidenceClass,ConfidenceOrder,ConfidenceFamily,ConfidenceGenus
ASV_2,AGCGCAGGCGGTTTCTTAAGTCTGATGTGAAAGCCCCCGGCTCAAC...,Bacteria,Firmicutes,Bacilli,Lactobacillales,Enterococcaceae,Enterococcus,azikeevi/casseliflavus/durans/faecalis/faecium...,100,100,100,100,100,96
ASV_8,AGCGCAGGCGGTTTGATAAGTCTGAAGTTAAAGGCTGTGGCTCAAC...,Bacteria,Firmicutes,Bacilli,Lactobacillales,Streptococcaceae,Streptococcus,NaN,100,100,100,100,100,100
ASV_6,GGAGCAGGCGGCAGCAAGGGTCTGTGGTGAAAGCCTGAAGCTTAAC...,Bacteria,Firmicutes,Bacilli,Erysipelotrichales,Erysipelatoclostridiaceae,Erysipelatoclostridium,ramosum,100,100,100,100,100,100
ASV_19,TGCGTAGGTGGCGTACTAAGTCTGTAGTAAAAGGCAATGGCTCAAC...,Bacteria,Firmicutes,Bacilli,Erysipelotrichales,Erysipelotrichaceae,[Clostridium] innocuum group,NaN,100,100,100,100,100,100
ASV_16,AGCGCAGGCGGTTTGATAAGTCTGAAGTTAAAGGCTGTGGCTCAAC...,Bacteria,Firmicutes,Bacilli,Lactobacillales,Streptococcaceae,Streptococcus,salivarius/thermophilus,100,100,100,100,100,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ASV_9992,GGAGCAGGCGGCAGCAAGGGTCTGTGGTGAAAGCCTGAAGCTTAAC...,Bacteria,Firmicutes,Bacilli,Erysipelotrichales,Erysipelatoclostridiaceae,Erysipelatoclostridium,NaN,100,100,100,100,100,100
ASV_9994,AGCGTAGACGGTGTTGCAAGTCTGATGTGAAAGGCGGGGGCTCAAC...,Bacteria,Firmicutes,Clostridia,Lachnospirales,Lachnospiraceae,Blautia,NaN,100,100,100,100,100,99
ASV_9996,AGCGTAGACGGAGCAGCAAGTCTGATGTGAAAACCCGGGGCTCAAC...,Bacteria,Firmicutes,Clostridia,Lachnospirales,Lachnospiraceae,[Ruminococcus] torques group,NaN,100,100,100,100,100,99
ASV_9997,AGCGTAGACGGTGTTGCAAGTCTGATGTGAAAGGCGGGGGCTCAAC...,Bacteria,Firmicutes,Clostridia,Lachnospirales,Lachnospiraceae,Blautia,NaN,100,100,100,100,100,90
ASV_9998,CACGCAGGCGGTCTGTCAAGTCGGATGTGAAATCCCCGGGCTCAAC...,Bacteria,Proteobacteria,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,NaN,100,100,100,100,100,84

In [33]:
df_new.to_csv("tblASVtaxonomy_silva138_bact.csv")

In [46]:
df_tax = pd.read_csv("tblASVtaxonomy_silva138_bact.csv")
df_count = pd.read_csv("tblcounts_melt_bact.csv")
assert len(set(df_count.ASV)-set(df_tax.ASV))==0

asvs_to_remove = list(set(df_tax.ASV)-set(df_count.ASV))
df_tax = df_tax[~df_tax.ASV.isin(asvs_to_remove)]
df_tax.to_csv("tblASVtaxonomy_silva138_bact.csv", index=False)