In [46]:
import pandas as pd
import numpy as np

# Read wbc data

In [84]:
dfb = pd.read_csv("../tblwbc_Brad.csv")
dfb['Unit'] = 'K_per_uL'
dfb = dfb[['PatientID','Timepoint','BloodCellType','Value','Unit','DayRelativeToNearestHCT']]
dfb['Priority_BT'] = 2
dfb.head()

/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,PatientID,Timepoint,BloodCellType,Value,Unit,DayRelativeToNearestHCT,Priority_BT
0,1001,7,WBCtotal,<0.1,K_per_uL,4,2
1,1001,8,WBCtotal,<0.1,K_per_uL,5,2
2,1001,9,WBCtotal,<0.1,K_per_uL,6,2
3,1001,11,WBCtotal,0,K_per_uL,8,2
4,1001,12,WBCtotal,<0.1,K_per_uL,9,2

In [92]:
set(dfb.BloodCellType)

{'Lymphocytes', 'Neutrophils', 'WBCtotal'}

In [85]:
dft = pd.read_csv("../tblwbc_tr.csv", index_col=0)
dft = dft[['MRN','test_date','WBC','Abs.Neut','Abs.Lymph','test_bmtday']]
dft.columns = ['MRN','Timepoint','WBCtotal','Neutrophils','Lymphocytes','DayRelativeToNearestHCT']
dft.MRN = dft.MRN.astype(int)
df_key = pd.read_csv('tCastoriPatientDictionaryWithDatesAndOtherStudiesPatientId.txt').rename({'cmicId':'PatientID'}, axis=1)
dft = pd.merge(dft, df_key[['MRN','PatientID','referenceDate']], left_on=['MRN'], right_on=['MRN'], how='inner')
dft = dft.drop('MRN', axis=1)
dft['Timepoint'] = pd.to_datetime(dft['Timepoint'], format='%Y-%m-%d')
dft['referenceDate'] = pd.to_datetime(dft['referenceDate'], format='%Y-%m-%d %H:%M:%S.%f')
dft['Timepoint'] = (dft['Timepoint']-dft['referenceDate']).dt.days
dft = dft.drop('referenceDate', axis=1)
dft = dft.set_index(['PatientID','Timepoint','DayRelativeToNearestHCT']).stack().reset_index()
dft.columns = ['PatientID','Timepoint','DayRelativeToNearestHCT','BloodCellType','Value']
dft['Unit'] = 'K_per_uL'
dft = dft[['PatientID','Timepoint','BloodCellType','Value','Unit','DayRelativeToNearestHCT']]
dft['Priority_TR'] = 1
dft.head()

,PatientID,Timepoint,BloodCellType,Value,Unit,DayRelativeToNearestHCT,Priority_TR
0,FMT.0069,1503,WBCtotal,5.5,K_per_uL,1488,1
1,FMT.0069,1503,Neutrophils,1.9,K_per_uL,1488,1
2,FMT.0069,1503,Lymphocytes,2.6,K_per_uL,1488,1
3,FMT.0069,-189,WBCtotal,1.6,K_per_uL,-204,1
4,FMT.0069,-189,Neutrophils,0.7,K_per_uL,-204,1

In [91]:
set(dft.BloodCellType)

{'Lymphocytes', 'Neutrophils', 'WBCtotal'}

In [93]:
dfj = pd.read_csv("../tblbc_js.csv")
dfj.Value = dfj.Value.astype(str)
dfj['Priority_JS'] = 3
dfj.head()

/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,PatientID,Timepoint,BloodCellType,Value,Unit,DayRelativeToNearestHCT,Priority_JS
0,1000,-427,Basophils,0.0,K_per_uL,-436,3
1,1000,-427,Eosinophils,0.0,K_per_uL,-436,3
2,1000,-427,Lymphocytes,1.5,K_per_uL,-436,3
3,1000,-427,Monocytes,0.3,K_per_uL,-436,3
4,1000,-427,Neutrophils,1.9,K_per_uL,-436,3

In [94]:
len(dfj)

1727327

# Join tables

In [76]:
df = pd.merge(dfj, dfb,
              left_on=['PatientID','Timepoint','BloodCellType','Value','Unit','DayRelativeToNearestHCT'],
              right_on=['PatientID','Timepoint','BloodCellType','Value','Unit','DayRelativeToNearestHCT'],
              how='outer'
             )
df = pd.merge(df, dft,
              left_on=['PatientID','Timepoint','BloodCellType','Value','Unit','DayRelativeToNearestHCT'],
              right_on=['PatientID','Timepoint','BloodCellType','Value','Unit','DayRelativeToNearestHCT'],
              how='outer'
             )
df[['Priority_JS','Priority_BT','Priority_TR']]=df[['Priority_JS','Priority_BT','Priority_TR']].fillna(0)
df['Priority'] = df[['Priority_JS','Priority_BT','Priority_TR']].max(axis=1)
df = df.sort_values(['PatientID','Timepoint','BloodCellType','Priority'])
df = df.loc[df[['PatientID','Timepoint','BloodCellType','Priority']].drop_duplicates().index]
df = df[['PatientID','Timepoint','BloodCellType','Value','Unit','DayRelativeToNearestHCT']]
df.to_csv("tblbc.csv", index=False)
df

,PatientID,Timepoint,BloodCellType,Value,Unit,DayRelativeToNearestHCT
8306,101,-1093,Basophils,0.1,K_per_uL,-1113
8307,101,-1093,Eosinophils,0.1,K_per_uL,-1113
8308,101,-1093,Lymphocytes,1.1,K_per_uL,-1113
8309,101,-1093,Monocytes,0.3,K_per_uL,-1113
8310,101,-1093,Neutrophils,0.8,K_per_uL,-1113
...,...,...,...,...,...,...
1727678,pt_with_samples_833_883,1765,Monocytes,0.6,K_per_uL,1562
1727679,pt_with_samples_833_883,1765,Neutrophils,3.8,K_per_uL,1562
1727680,pt_with_samples_833_883,1765,Platelets,272.0,K_per_uL,1562
1727681,pt_with_samples_833_883,1765,RBCtotal,3.32,M_per_uL,1562
1727682,pt_with_samples_833_883,1765,WBCtotal,6.6,K_per_uL,1562